# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0d40173c534cfceedad341f764c944bbdcf715effacbef19c3902820b5eafe49e97abbfec7579cdd14e12d00fad31c735fbad0c9f3e1365a1958284d1b5b20

test:
  secret_key_base: 38494ef906dd6045691c9cb774af681ce2b1748e3115d0570020693256d8a0cdf02d2afa5dadca247f1adf14d969733d6bfff920914613f68d914c421507741b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
